spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
